### ISSUE TITLE
Let us be able to turn images into maps

### ISSUE THREAD

**Issue by sugmagaming** [apetavern/grubs#198]
Let us turn an image into a map. Make a certain color like black or green be transparent, aka no map, and the rest of the colors show and be the map.  This is an iconic and ESSENTIAL worm feature. I swear to god if you do not add this I will mail a pipe bomb to Ape Tavern studios.  Here is an example.
![wurmms](https://user-images.githubusercontent.com/15720147/226111400-14d28fbb-62bc-421f-aae6-bcbaf73db26d.png)

**Comment by trundler-dev** [comment]
This is something we'd like to do in the future, but it is not currently possible with the terrain library we are using. To that end, this is low priority until we are happy where Grubs is at, and have more time to dedicate to features such as this.

**Comment by ShadowBrian** [comment]
This is currently basically possible but we don't apply any kind of image to the shapes yet so the texture would just be ground shaped.
Feels like a possibility now though.
