### ISSUE TITLE
UI sometimes breaks and shows double, plus shows players as disconnected

### ISSUE THREAD

**Issue by trundlr** [apetavern/grubs#244]
![image](https://github.com/apetavern/sbox-grubs/assets/57276947/f40aa473-e71c-4eb6-acea-41bae03ad88a)

Could be related to unreliability of ClientRpcs, but clearly something networking related is breaking here.

**Comment by matekdev** [comment]
As mentioned, let's assign the hud entity to a singleton which only gets assigned if the singleton is null. Let's see if that fixes it up.

**Comment by matekdev** [comment]
I might have fixed this, lets see if anyone else reports on it.

**Comment by trundlr** [comment]
Should be resolved as entities are no more!
