### ISSUE TITLE
Re-add world hud for health popups and crate popups

### ISSUE THREAD

**Issue by trundlr** [apetavern/grubs#342]
https://github.com/apetavern/grubs/tree/4ff157082d4a18504a97320159bcae28b41e140e/code/UI/World

We do not have an event system in s&box anymore - we can call a Singleton component method instead, probably.

**Comment by DrewBritt** [comment]
Only thing missing to my knowledge is the panel fading out; apparently ```&:outro``` hasn't been working for WorldPanels for some time?

https://github.com/apetavern/grubs/assets/43252311/3cde16e9-bf39-43b6-bef8-4e33b3aad2fd

https://github.com/apetavern/grubs/assets/43252311/5708cec2-1d44-4773-86db-e1d0d0ab06c6

**Comment by trundlr** [comment]
We can address fade out later! Nice work.
