### ISSUE TITLE
Re-add chatbox

### ISSUE THREAD

**Issue by trundlr** [apetavern/grubs#345]
Create a chatbox, similar to the old chatbox. Player should be able to type, send emojis, etc. The game log (such as "A health crate has spawned" will feed into this, but feel free to ignore that portion for now.

**Comment by DrewBritt** [comment]
https://github.com/apetavern/grubs/commit/426a69fa0adce28dc0f986d264fd5593ac61cdf9 https://github.com/apetavern/grubs/commit/3c90353c0218027783bc996b48daa8252b1a7078

https://github.com/apetavern/grubs/assets/43252311/e342c028-6760-4a59-96da-65942ba7c917

https://github.com/apetavern/grubs/assets/43252311/b84a3fec-a644-4c8f-aa83-3f2c27965e85

**Comment by trundlr** [comment]
Great work!
