### ISSUE TITLE
Show ammo HUD for weapons that can be fired multiple times

### ISSUE THREAD

**Issue by trundlr** [apetavern/grubs#348]
We need an ammo count in the HUD for weapons that can fired multiple times (such as Shotgun).

This could be screen UI somewhere on the screen or world UI near the Grub. Feel free to just experiment and we can reach UI consensus together.

**Comment by DrewBritt** [comment]
https://github.com/apetavern/grubs/assets/43252311/b6ba1cc9-0479-4e35-a77c-5ae1b735c4b6
