### ISSUE TITLE
Generic throwable magic weapon, which has switchable elemental types

### ISSUE THREAD

**Issue by trundlr** [apetavern/grubs#350]
This task is for tracking progress on art for the new magic weapon.

The weapon will be throwable, can take on multiple different types of elements (fire, sludge, etc).

Ideally, we have a consistent model / particle that can be coloured to match a certain element colour. Furthermore, we want to have ground effects (similar to scorch ground effects) for each type of element.

- [ ] Base particle or model for an elemental ball
- [ ] Can be tinted to match different element styles

**Comment by Jammie3d** [comment]
Made a start on the art in the [magic-missile](https://github.com/apetavern/grubs/tree/magic-missile) branch
