### ISSUE TITLE
Fix brass knuckles

### ISSUE THREAD

**Issue by trundlr** [apetavern/grubs#351]
The multi-hit melee weapon component is currently not hooked up properly. Just ensure it behaves as expected (hits three times, each hit has a different animation), and calls FireFinished as expected.

**Comment by cs716** [comment]
https://github.com/apetavern/grubs/commit/f7233b54eabc96e6b7247de1be413a9869ad04d1
https://github.com/apetavern/grubs/commit/09d019f35672e297306ee135f6ebbebf8854698e
https://github.com/apetavern/grubs/commit/731495b7ee6f558ef90c7e623e61b304a796a155
