### ISSUE TITLE
Grubs not properly dying

### ISSUE THREAD

**Issue by cs716** [apetavern/grubs#385]
Grubs will sometimes get stuck in the plunger animation and remain alive with 0 health

**Comment by DrewBritt** [comment]
https://github.com/apetavern/grubs/commit/f74ad68856f60cb4664f8eb34f228f57feab5ecf

This was due to DeathReason.ToString() freaking out and causing the death animation task to throw.

**Comment by cs716** [comment]
Still occurring 
![image](https://github.com/apetavern/grubs/assets/29966072/3e50cad5-d37c-4c58-9587-5dcab590e05d)

**Comment by DrewBritt** [comment]
https://github.com/apetavern/grubs/commit/917e8ae73dad751bdf9293ba52498145745471b0

I tested a bunch of scenarios both locally and over the network and couldn't get it to NRE. I also took the opportunity to make sure we were getting/using all damage information, and did some cleanup.
