### ISSUE TITLE
Clean up landmines / oildrums / etc when game is over

### ISSUE THREAD

**Issue by trundlr** [apetavern/grubs#387]
Currently, these networked objects belong to the host, but I don't think they are stored anywhere for easy reference. We need a method that cleans them up that we can run when cleaning up terrain / grubs / etc.

**Comment by cs716** [comment]
It looks like all of the cursors get left behind too
![image](https://github.com/apetavern/grubs/assets/29966072/c6c5dc1d-c319-4bbe-b47d-aa30cde5d036)

Would it be too much to add a "temporary" tag and perform a cleanup on those @trundlr ?

**Comment by cs716** [comment]
Hope not I did it - tag is "cleanup"

https://github.com/apetavern/grubs/assets/29966072/cd616eea-c3c3-45c1-913f-bfc1f5613247
