### ISSUE TITLE
Fix spawns not being safe or causing projectiles to immediately fall off the map

### ISSUE THREAD

**Issue by trundlr** [apetavern/grubs#388]

**Comment by DrewBritt** [comment]
https://github.com/apetavern/grubs/commit/9805c07e5f72878dc9c01e05be1f127b7e30335b

Seemed ok in my testing but we should leave this open until after we do playtesting.

**Comment by ShadowBrian** [comment]
I ran some tests setting grub_count to 10 and setting different texture terrains, seems a lot better if not entirely fixed.

**Comment by trundlr** [comment]
I think this is still an issue for crates/oildrums/etc.
