### ISSUE TITLE
Jetpack - Inconsistent handling

### ISSUE THREAD

**Issue by cs716** [apetavern/grubs#393]
- Jetpack will sometimes handle extremely slowly making it unusable. 
- This was typically noticed only if the grub was between terrain (like in a narrow cavern) or the first time the jetpack is used for that match. Not sure which was the cause.

**Comment by DrewBritt** [comment]
https://github.com/apetavern/grubs/commit/60079ab681245e013328b1cad07b48fb92cfced7
