### ISSUE TITLE
Double HP bars if too many players 

### ISSUE THREAD

**Issue by cs716** [apetavern/grubs#410]
![image](https://github.com/apetavern/grubs/assets/29966072/6ed36717-54f5-40ab-b381-e9d5e44847b0)

**Comment by DrewBritt** [comment]
I honestly think this was a mix of the bug seen in https://github.com/apetavern/grubs/issues/404 and a player (it was Borris IIRC) leaving mid-game. Both of these should be fixed by now, but this scenario is hard to test by myself thoroughly, so I'll leave this open until after the next playtest.
